
```{r}
# load libraries
set.seed(1234)
set.seed(1234)
source("data_preparation_scripts/1_load_libraries.R")
# read in data
source("data_preparation_scripts/2_read_in_data.R") # Reads in GPANEL and EVS data
source("data_preparation_scripts/3_add_socio_demographics.R") # add standardized socio-demographic variables to GPANEL and EVS datasets
source("data_preparation_scripts/4_get_population_marginals.R") # get population marginals from official statistics
# loads a wrapper function for raking
source("data_preparation_scripts/5_raking.R")

```


# Data preparation

This code chunk has three purposes:
1. GPANEL and EVS are imputed 
2. Raking weights are created for GPANEL and EVS
3. A dataset with 17 candidate instrument pairs is created for both surveys.

```{r}

# get intstrument pairs and grouping_variables


instrument_pairs <- read_excel("list_of_instrument_pairs/instrument_pairs_17.xlsx") %>% mutate(
  filter_source = filter_source %>% as.logical(),
  filter_target = filter_target %>% as.logical(),
  source_invert = source_invert %>% as.logical(),
  target_invert = target_invert %>% as.logical()
)
grouping_variabels <- c("east_west", "sex", "age_cat", "edu")

all_weight_names <- get_labels(full_gpanel) %>%
  filter(str_detect(value, "weight")) %>%
  pull(name)
map_chr(str_sub(instrument_pairs$source, 1, 2), ~
  all_weight_names[str_detect(
    all_weight_names,
    paste0("^", .x, "za.*07a", "$")
  )])
grouping_variabels_int <- grouping_variabels %>% map_chr(~ paste0(.x, "_i"))


# impute and rake variables
#####################
## EVS


# getting variables to impute
evs_to_impute <- evs_17 %>%
  select(instrument_pairs$target, grouping_variabels_int) %>%
  mutate(across(everything(), ~ as.integer(.x)))




# impute
evs_imputed <- mice(evs_to_impute, m = 1, maxit = 1, method = "pmm")
imputed_grouping_vars_evs <- complete(evs_imputed) %>%
  select(all_of(grouping_variabels_int)) %>%
  rename_with(.cols = everything(), .fn = ~grouping_variabels)

# create factor with correct levels and labels & overwrite grouping vars with imputed grouping vars
evs_17 <- evs_17 %>% imodify(~ {
  if (.y %in% grouping_variabels) {
    factor(
      x = imputed_grouping_vars_evs %>% pull(!!sym(.y)),
      levels = evs_17 %>% pull(!!sym(paste0(.y, "_f"))) %>% fct_anon() %>% levels(),
      labels = levels(evs_17 %>% pull(!!sym(paste0(.y, "_f"))))
    )
  } else {
    .x
  }
})


# adding raked weights evs
evs_17_raked <- evs_17 %>%
  filter(age_cat != "unter 20") %>%
  mutate(raked_weights = create_weigths(evs_17 %>%
    filter(age_cat != "unter 20"),
  "dweight",
  grouping_variabels = grouping_variabels,
  pop_margins = pop_marg
  )) # returnes standardized and trimmed weights


# check results
# map(instrument_pairs$target,
#    ~evs_17_raked %>%
#      group_by(!!sym(.x)) %>%
#      summarize(unweighted_freq=n(),
#                raked_weights=sum(raked_weights,na.rm=T)))
#

#################
# GESIS Panel
# impute GESIS Panel
to_impute_gpanel <- full_gpanel %>%
  filter(age_cat != "unter 20") %>%
  select(contains(grouping_variabels_int), all_of(instrument_pairs$source)) %>%
  drop_na(east_west_i) # east west NAs are rows with only NAs
id_vec <- full_gpanel %>%
  filter(age_cat != "unter 20") %>%
  drop_na(east_west_i) %>%
  select(z000001a) # id vector to bind imputed values to full gesis panel later




# 1. get the full data with negative values as NA
to_impute_gpanel <- to_impute_gpanel %>%
  mutate(across(-all_of(grouping_variabels_int), ~ if_else(.x > 0, as.numeric(.x), NA_real_)))




# 2. impute
imputed <- mice(to_impute_gpanel, m = 1, maxit = 1, method = "pmm", )
imputed_grouping_vars <- complete(imputed) %>%
  as_tibble() %>%
  select(all_of(grouping_variabels_int)) %>%
  rename_with(~grouping_variabels) %>%
  bind_cols(id_vec)



# replace unimputed grouping variables with imputed variables
to_rake_gpanel <- full_gpanel %>%
  select(z000001a, all_of(c(instrument_pairs$source, all_weight_names))) %>%
  left_join(imputed_grouping_vars, by = "z000001a") %>%
  imodify(~ if (.y %in% grouping_variabels) {
    factor(
      x = .x,
      levels = full_gpanel %>% pull(!!sym(paste0(.y, "_f"))) %>% fct_anon() %>% levels(),
      labels = levels(full_gpanel %>% pull(!!sym(paste0(.y, "_f"))))
    )
  } else {
    .x
  }) %>%
  drop_na(east_west)


# raking for multiple waves
task_df <- map_df(
  instrument_pairs$source,
  ~ tibble(
    source = .x,
    weight = all_weight_names[str_detect(all_weight_names, str_sub(.x, 1, 2))]
  )
) %>% distinct(weight)

raked_weights <- map_df(task_df$weight, ~ {
  var <- sym(.x)
  data <- to_rake_gpanel %>% filter(!!var > 0)
  raked_weights <- create_weigths(
    df = data,
    name_of_design_weight = .x,
    grouping_variabels = grouping_variabels,
    pop_margins = pop_marg
  ) # returns standardized and trimmed weights

  results <- tibble(
    z000001a = data$z000001a,
    wave = paste0(.x, "_raked_weights"),
    raked_weights
  )
}) %>% pivot_wider(id_cols = z000001a, names_from = wave, values_from = raked_weights)




# add weights to full gpanel file
gpanel_raked <- full_gpanel %>%
  select(z000001a, all_of(c(grouping_variabels, instrument_pairs$source, all_weight_names))) %>%
  left_join(raked_weights)


# check results
task_df <- map_df(
  instrument_pairs$source,
  ~ tibble(
    source = .x,
    weight = all_weight_names[str_detect(all_weight_names, str_sub(.x, 1, 2))]
  )
)


```

```{r}
# loads functions which fetch data for the equating process
source("data_preparation_scripts/7_fetch_data_for_equating.R")
# loads function which does the actual equating
source("data_preparation_scripts/8_group_equating.R")
# execute the equating with the previously loaded data
source("data_preparation_scripts/9_perform_equating.R")
# create analysis data
source("data_preparation_scripts/10_prepare_harmonized_data_for_analysis.R")
# calculate r alerting values for 16 instrument pairs
source("data_preparation_scripts/11_r_alerting.R")

```


```{r}
r_alerting %>%
  group_by(reference_instrument) %>%
  summarize(estimate = cor.test(psych::fisherz(r_gpanel),psych::fisherz(r_evs))$estimate,
            upr = cor.test(psych::fisherz(r_gpanel),psych::fisherz(r_evs))$conf.int[1],
            lwr = cor.test(psych::fisherz(r_gpanel),psych::fisherz(r_evs))$conf.int[2]) %>%
  filter(!(reference_instrument %in% grouping_variabels)) %>%
  ggplot(aes(x=estimate,
             y=reorder(str_to_sentence(reference_instrument),estimate),
             xmin=lwr,
             xmax=upr))+
           geom_pointrange()+theme_classic(base_size = 20)+ theme(axis.text.x = element_text(angle = 80, vjust = 1, hjust=1))+labs(x = "r-alerting\n(95% CI)",y = "Instrument pairs")+
  lims(x = c(-0.1,1))

ggsave("figures/appendix_1_1.svg")
```

